
GET http://localhost:5181
###

GET http://localhost:5181/hello
###

POST  http://localhost:5181/hello
###

PUT  http://localhost:5181/hello
###

PATCH  http://localhost:5181/hello
###


DELETE  http://localhost:5181/hello

###
GET http://localhost:5181/products